/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "stm32f103c8.h"
#include "stm32f103c8_rcc_driver.h"
#include "stm32f103c8_gpio_driver.h"
#include "stm32f103c8_exti_driver.h"

#include "core_cm3.h"

#include "FreeRTOS.h"
#include "FreeRTOSConfig.h"
#include "task.h"
#include "semphr.h"

uint8_t CurrFlag = 0;
uint8_t PrevFlag = 0;

/* Semaphore Handle */
SemaphoreHandle_t xSemaphore1 = NULL;

/* Task Handle */
TaskHandle_t vPushButtonHandle = NULL;
TaskHandle_t vLedHandle = NULL;


/* Task Prototype */
void vPushButton(void *param);
void vLed(void *param);

void systemInit(void)
{


	MCAL_RCC_initSYSClk();

	MCAL_RCC_enableCLK(RCC_APB2_BUS, RCC_GPIOB_ID);

	GPIO_PinConfig_t config;

	config.GPIO_Mode = GPIO_MODE_INPUT_FLOATING;
	config.GPIO_PinNumber = GPIO_PIN1;
	MCAL_GPIO_Init(GPIOA, &config);

	config.GPIO_Mode = GPIO_MODE_OUTPUT_PUSHPULL;
	config.GPIO_PinNumber = GPIO_PIN13;
	config.GPIO_Output_Speed = GPIO_OUTPUT_SPEED_10M;
	MCAL_GPIO_Init(GPIOC, &config);
}

void vPushButton(void *param)
{
	while(1)
	{

		CurrFlag = MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN1);

		if(CurrFlag != PrevFlag)
		{
			xSemaphoreGive(xSemaphore1);
		}
		PrevFlag = CurrFlag;
		vTaskDelay(25);
	}
}

void vLed(void *param)
{
	while(1)
	{
		if(xSemaphoreTake(xSemaphore1, (TickType_t)5 ) == pdTRUE)
		{
			if(CurrFlag == 1)
			{
				MCAL_GPIO_WritePin(GPIOC, GPIO_PIN13, LOGIC_HIGH);
			}else
			{
				MCAL_GPIO_WritePin(GPIOC, GPIO_PIN13, LOGIC_LOW);
			}
		}
		vTaskDelay(25);
	}
}

int main(void)
{
	systemInit();

	xTaskCreate(vLed, "Led", 128, NULL, 1, vLedHandle);
	xTaskCreate(vPushButton, "PushButton", 128, NULL, 2, vPushButtonHandle);

	xSemaphore1 = xSemaphoreCreateBinary();

	vTaskStartScheduler();

	/* Loop forever */
	while(1);
}
